# Generated by Django 3.1.4 on 2021-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='unit',
            field=models.CharField(max_length=240),
        ),
    ]
