# Generated by Django 3.1.4 on 2020-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Doctor'), (1, 'Pharmacist'), (2, 'Patient'), (3, 'admin')], default=3),
        ),
    ]
