# Generated by Django 3.1.4 on 2020-12-31 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ward', models.CharField(max_length=300)),
                ('specialist', models.CharField(max_length=300)),
                ('note_to_specialist', models.CharField(max_length=300)),
                ('current_prescriptions', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=300)),
                ('note_to_specialist', models.CharField(max_length=300)),
                ('current_prescriptions', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=1000)),
                ('temparature', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=1000)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
