# Generated by Django 3.1.4 on 2020-12-29 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sub_county', models.CharField(max_length=250)),
                ('hospital_level', models.CharField(choices=[(1, 'Community Facilities'), (2, 'Health Dispensaries'), (3, 'Health Centres'), (4, 'County Hospitals'), (5, 'County Referral Hospitals'), (6, 'National Referral Hospitals')], default=1, max_length=250)),
                ('is_referral', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=25)),
            ],
        ),
    ]
