# Generated by Django 3.1.4 on 2020-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_level',
            field=models.CharField(choices=[('1', 'Community Facilities'), ('2', 'Health Dispensaries'), ('3', 'Health Centres'), ('4', 'County Hospitals'), ('5', 'County Referral Hospitals'), ('6', 'National Referral Hospitals')], default=1, max_length=250),
        ),
    ]
